# your-repo-name/.github/workflows/first_workflow.yml
name: Test with pytest                                    
on: 
  push:
    branches:
      - dev
jobs:                         
  first-job:                           
    name: Say hi                           
    runs-on: window-latest                           
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@main
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        if [ -d tests ] || [ -d test ]; then python -m pytest; fi
